### CREATE PRODUCTO
POST http://localhost:3000/api/v1/productos
Content-Type: application/json

{
  "producto": "Lapiz",
  "stockAmount": 5
}

###

### GET ALL PRODUCTOS
GET http://localhost:3000/api/v1/productos

###

### GET PRODUCTO BY ID 
GET http://localhost:3000/api/v1/productos/1

###

### UPDATE SIN AUTH (debe fallar 401)
PUT http://localhost:3000/api/v1/productos/5
Content-Type: application/json

{
  "stockAmount": 10
}

###

### UPDATE CON API KEY (debe funcionar)
PUT http://localhost:3000/api/v1/productos/5
Content-Type: application/json
x-api-key: supersecreta123

{
  "stockAmount": 10
}

###

### DELETE SIN AUTH (debe fallar 401)
DELETE http://localhost:3000/api/v1/productos/1

###

### DELETE CON API KEY (debe funcionar)
DELETE http://localhost:3000/api/v1/productos/1
x-api-key: supersecreta123